version: '3.8'

services:
  # Test runner service
  test-runner:
    build:
      context: .
      dockerfile: nookwriter-optimized.dockerfile
      args:
        BUILD_MODE: writer
    image: nook-test:latest
    container_name: nook-test-runner
    command: /tests/run-tests.sh
    volumes:
      - ./tests:/tests:ro
      - ./config:/config:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TERM=linux
      - CI=true
    profiles:
      - test

  # Test minimal mode
  test-minimal:
    build:
      context: .
      dockerfile: nookwriter-optimized.dockerfile
      args:
        BUILD_MODE: minimal
    image: nook-test-minimal:latest
    container_name: nook-test-minimal
    command: |
      sh -c "
        echo 'Testing minimal mode...'
        vim --version | head -1
        free -h
        echo 'Minimal mode test passed'
      "
    mem_limit: 256m
    memswap_limit: 256m
    profiles:
      - test

  # Test writer mode
  test-writer:
    build:
      context: .
      dockerfile: nookwriter-optimized.dockerfile
      args:
        BUILD_MODE: writer
    image: nook-test-writer:latest
    container_name: nook-test-writer
    command: |
      sh -c "
        echo 'Testing writer mode...'
        vim --version | head -1
        ls -la /root/.vim/pack/plugins/start/ 2>/dev/null || echo 'No plugins (expected for minimal)'
        free -h
        echo 'Writer mode test passed'
      "
    mem_limit: 256m
    memswap_limit: 256m
    profiles:
      - test

  # Memory usage comparison
  memory-test:
    image: alpine:latest
    container_name: memory-test
    command: |
      sh -c "
        apk add --no-cache docker-cli
        echo '=== Memory Usage Test ==='
        docker stats --no-stream --format 'table {{.Container}}\t{{.MemUsage}}' nook-test-minimal nook-test-writer 2>/dev/null || echo 'Start test containers first'
      "
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    profiles:
      - memory