version: '3.8'

services:
  # Minimal mode - no plugins, 2MB RAM
  nook-minimal:
    build:
      context: .
      dockerfile: nookwriter-optimized.dockerfile
      args:
        BUILD_MODE: minimal
    image: nook-minimal:latest
    container_name: nook-minimal
    restart: unless-stopped
    volumes:
      - ./data:/root/data
      - ./notes:/root/notes
    environment:
      - TERM=linux
      - EDITOR=vim
    stdin_open: true
    tty: true
    # Limit memory to simulate Nook
    mem_limit: 256m
    memswap_limit: 256m
    healthcheck:
      test: ["CMD-SHELL", "command -v vim >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Writer mode - Goyo + Pencil, 5MB RAM  
  nook-writer:
    build:
      context: .
      dockerfile: nookwriter-optimized.dockerfile
      args:
        BUILD_MODE: writer
    image: nook-writer:latest
    container_name: nook-writer
    restart: unless-stopped
    volumes:
      - ./data:/root/data
      - ./notes:/root/notes
    environment:
      - TERM=linux
      - EDITOR=vim
    stdin_open: true
    tty: true
    # Limit memory to simulate Nook
    mem_limit: 256m
    memswap_limit: 256m
    healthcheck:
      test: ["CMD-SHELL", "command -v vim >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Original full-featured version for comparison
  nook-standard:
    build:
      context: .
      dockerfile: nookwriter.dockerfile
    image: nook-standard:latest
    container_name: nook-standard
    restart: unless-stopped
    volumes:
      - ./config:/root/config:ro
      - ./data:/root/data
      - ./notes:/root/notes
    environment:
      - TERM=xterm-256color
      - EDITOR=vim
      - PAGER=less
    stdin_open: true
    tty: true
    # Limit memory to simulate Nook
    mem_limit: 256m
    memswap_limit: 256m
    healthcheck:
      test: ["CMD-SHELL", "command -v vim >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Test environment to compare RAM usage
  ram-test:
    image: alpine:latest
    container_name: ram-test
    command: |
      sh -c "
      while true; do
        echo '=== RAM Usage Comparison ==='
        docker stats --no-stream --format 'table {{.Container}}\t{{.MemUsage}}' nook-minimal nook-writer nook-standard 2>/dev/null || echo 'Start containers first'
        sleep 30
      done
      "
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    profiles:
      - monitoring