version: '3.8'

services:
  nookwriter:
    build:
      context: .
      dockerfile: nookwriter.dockerfile
    container_name: nookwriter
    restart: unless-stopped
    volumes:
      - ./config:/root/config:ro
      - ./data:/root/data
    environment:
      - TERM=xterm-256color
      - EDITOR=vim
      - PAGER=less
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "command -v vim >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s