" Minimal vimrc for Nook writing environment
set nocompatible
set ttyfast
set backspace=indent,eol,start
set number
set wrap
set linebreak
set textwidth=0
set spell
syntax on
filetype plugin indent on

" Simple leader mappings for writing modes
let mapleader = " "
nnoremap <leader>zn :e ~/notes/<C-R>=strftime("%Y%m%d%H%M%S")<CR>.md<CR>
nnoremap <leader>dd :e ~/drafts/draft.txt<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>

" Enable plugins
set runtimepath^=~/.vim/pack/plugins/start